config/routes.rb
Whackbackend::Application.routes.draw do
  root :to => "Complaints#new"
  resources :users
  resources :sessions
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "signup" => "users#new"

  post "complaints/close"
  get "complaints/status"
  post "complaints/upload/:id" => 'Complaints#upload_pic'
  resources :complaints
  

end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
  OPEN = "Open"
  CLOSED = "Closed"

  validates_presence_of :mobile, :location, :complaint_type
  
  def turn_around_time

    distance_in_hours   = (((updated_at - created_at).abs) / 3600).round
    distance_in_minutes = ((((updated_at - created_at).abs) % 3600) / 60).round

    difference_in_words = ''

    difference_in_words << "#{distance_in_hours} #{distance_in_hours > 1 ? 'hours' : 'hour' } and " if distance_in_hours > 0
    difference_in_words << "#{distance_in_minutes} #{distance_in_minutes == 1 ? 'minute' : 'minutes' }"
  end

  
  def complaint_types
    {
      "No Water Supply" => "WS",
      "Water Leak" => "WL",
      "Dumping of the waste in Lake" => "WD"
    }
  end
end

app/controllers/complaint_controller.rb
require 'uuid'
include Geokit::Geocoders

class ComplaintController < ApplicationController
  SUCCESSFULLY_REGISTERED = "Complaint was successfully registered"
  MATCH_NOT_FOUND = "Could not find complaint matching the input" 
  SUCCESSFULLY_RESOLVED = "Complaint marked as resolved"
  NEED_TO_CORRECT_DATA = "Provide correct mobile number and complaint id"
  MATCH_FOUND = "Found matching complaint"
  COULDNOT_REGISTER_COMPLAINT = "Could not register complaint. Ensure that location and complaint type are provided"
  
  def index
    @complaints = Complaint.all
    respond_to do |f|
      f.html
    end
  end
  def upload_pic
    puts 'Inside Upload Pic'
    puts params
    file = params['file']
    fileName = params['id'] + '.png'
    puts "#{file} #{fileName}"
    directory = "/Users/senthilkumarv/data"
    path = File.join(directory, fileName)
    File.open(path, "wb") { |f| f.write(file.read) }
    render :nothing => true
  end
  def show
    @complaint = Complaint.find_by_id params["id"]

    respond_to do |f|
      f.html
    end
  end
  
  def create
    complaint = complaint_from params
    if complaint.save
      response = json_from(:response => 201,
                           :reference_id => complaint.reference_id,
                           :message => SUCCESSFULLY_REGISTERED,
                           :status => complaint.status)
    else
      response = json_from(:response => 507,
                           :reference_id => "",
                           :status => "NA",
                           :message => COULDNOT_REGISTER_COMPLAINT)
    end

    set_json_response response
  end

  def close
    if params["reference_id"] && params["mobile"]
      complaint = Complaint.find_by_reference_id params["reference_id"]
      if complaint && complaint.mobile == params["mobile"]
        complaint.status = "Closed"
        complaint.save
      end
    else
      complaint = nil
    end


    if complaint
      response = json_from(:response => 200,
                           :message => SUCCESSFULLY_RESOLVED,
                           :status => complaint.status,
                           :reference_id => complaint.reference_id)
    else
      response = json_from(:response => 404,
                           :message => NEED_TO_CORRECT_DATA,
                           :status => "NA",
                           :reference_id => "NA")
    end

    set_json_response response
  end
  
  def status
    if params["reference_id"]
      complaint = Complaint.find_by_reference_id params["reference_id"]
    elsif params["mobile"]
      complaint = Complaint.find_all_by_mobile(params["mobile"]).last
    end
    if complaint
      response = json_from(:response => 200,
                           :status => complaint.status,
                           :message => MATCH_FOUND,
                           :reference_id => complaint.reference_id)
    else
      response = json_from(:response => 404,
                           :message => MATCH_NOT_FOUND,
                           :status => "NA",
                           :reference_id => "NA")
    end

    set_json_response response
  end
  
  def upload_file
    puts params
  end

  def feed
    complaints = Complaint.all
    respond_to do |format|
      format.json {
        render :json => complaints.to_json
      }
      format.xml {
        render :xml => complaints.to_xml
      }
    end
  end
  
  def report
    @complaints_ws = Complaint.find_all_by_complaint_type('WS')
    @complaints_wl = Complaint.find_all_by_complaint_type('WL')
    @complaints_wd = Complaint.find_all_by_complaint_type('WD')
    respond_to do |format|
      format.html
    end
  end
  
  private
  def json_from map
    map.to_json
  end

  def set_json_response response
    respond_to do |format|
      format.json {
        render :json => response
      }
      
    end
  end
  
  def complaint_from params
    complaint = Complaint.new
    complaint.mobile = params["mobile"]
    if params["location"] 
      complaint.location = params["location"] 
      complaint.latitude = GoogleGeocoder.do_geocode(complaint.location).lat
      complaint.longitude  = GoogleGeocoder.do_geocode(complaint.location).lng
    elsif(params["lat"] && params["lng"])
      complaint.latitude =  params["lat"]
      complaint.longitude = params["lng"]
      loc = GoogleGeocoder.do_reverse_geocode([params["lat"], params["lng"]])
      complaint.location = loc.full_address
    end
    complaint.photo_url = "No Photo Attached"
    complaint.photo_url = params["photo_url"] if params["photo_url"]
    complaint.name = "Anonymous"
    complaint.name = params["name"] if params["name"]
    complaint.complaint_type = params["type"]
    puts complaint.complaint_type
    complaint.reference_id = DateTime.now.updated_at.to_i.abs
    complaint.status = "Open"
    complaint
  end
end

app/controllers/complaints_controller.rb
require 'uuid'
include Geokit::Geocoders

class ComplaintsController < ApplicationController
  include RedirectHelper

  SUCCESSFULLY_REGISTERED = "Complaint was successfully registered"
  MATCH_NOT_FOUND = "Could not find complaint matching the input" 
  SUCCESSFULLY_RESOLVED = "Complaint marked as resolved"
  NEED_TO_CORRECT_DATA = "Provide correct mobile number and complaint id"
  MATCH_FOUND = "Found matching complaint"
  COULDNOT_REGISTER_COMPLAINT = "Could not register complaint. Ensure that location and complaint type are provided"
  
  def index
    @complaints = Complaint.all
    respond_to do |format|
      format.html
      format.json do
        render :json => remove_phone_numbers(@complaints).to_json
      end

      format.xml do
        render :xml => remove_phone_numbers(@complaints).to_xml
      end

      format.rss do
        render :layout => false
      end
    end
  end
  
  def new
    @complaint = Complaint.new

    respond_to do |format|
      format.html
    end
  end
  
  def upload_pic
    puts params
    file = params['file']
    fileName = params['id'] + '.png'
    puts "#{file} #{fileName}"
    directory = File.join(Rails.root, "data")
    path = File.join(directory, fileName)
    File.open(path, "wb") { |f| f.write(file.read) }
    render :nothing => true
  end

  # def show
  #   @complaint = Complaint.find_by_id params["id"]

  #   respond_to do |format|
  #     format.html
  #   end
  # end

  def destroy
    complaint = Complaint.find(params[:id])
    complaint.status = 'Closed'
    complaint.save
    respond_to do |format|
      format.html
      
      format.json do
        render :json => json_from(:response => 200,
                                  :message => SUCCESSFULLY_RESOLVED,
                                  :status => complaint.status,
                                  :reference_id => complaint.reference_id)
        
      end
    end
  end
  
  def create
    @complaint = complaint_from params
    respond_to do |format|
      format.json do
        if @complaint.save
          render :json => json_from(:response => 200,
                                    :reference_id => @complaint.reference_id,
                                    :message => SUCCESSFULLY_REGISTERED,
                                    :status => @complaint.status)
        else
          render :json => json_from(:response => 507,
                                    :reference_id => "",
                                    :status => "NA",
                                    :message => COULDNOT_REGISTER_COMPLAINT)
        end
      end
    end
  end

  def close
    if params["reference_id"] && params["mobile"]
      complaint = Complaint.find_by_reference_id params["reference_id"]
      if complaint && complaint.mobile == params["mobile"]
        complaint.status = "Closed"
        complaint.save
      end
    else
      complaint = nil
    end


    if complaint
      response = json_from(:response => 200,
                           :message => SUCCESSFULLY_RESOLVED,
                           :status => complaint.status,
                           :reference_id => complaint.reference_id)
    else
      response = json_from(:response => 404,
                           :message => NEED_TO_CORRECT_DATA,
                           :status => "NA",
                           :reference_id => "NA")
    end

    set_json_response response
  end
  
  def show
    if params["id"]
      complaint = Complaint.find_by_reference_id params["id"]
    # elsif params["mobile"]
    #   complaint = Complaint.find_all_by_mobile(params["mobile"]).last
    end
    if complaint
      set_json_response json_from(:status => complaint.status)
    else
      set_json_response json_from({}), 404
    end

  end
  
  def upload_file
    puts params
  end
  
  def report
    @complaints_ws = Complaint.find_all_by_complaint_type('WS')
    @complaints_wl = Complaint.find_all_by_complaint_type('WL')
    @complaints_wd = Complaint.find_all_by_complaint_type('WD')
    respond_to do |format|
      format.html
    end
  end
  
  private
  def json_from map
    map.to_json
  end

  def set_json_response response, status = 200
    respond_to do |format|
      format.json {
        render :json => response, :status => status
      }
      
    end
  end
  
  def complaint_from params
    complaint = Complaint.new params[:complaint]
    if complaint.location 
      complaint.latitude = GoogleGeocoder.do_geocode(complaint.location).lat
      complaint.longitude  = GoogleGeocoder.do_geocode(complaint.location).lng
    elsif(complaint.latitude && complaint.longitude)
      loc = GoogleGeocoder.do_reverse_geocode([params["lat"], params["lng"]])
      complaint.location = loc.full_address
    end
    complaint.photo_url = "No Photo Attached" unless complaint.photo_url
    complaint.name = "Anonymous" unless complaint.name
    complaint.reference_id = DateTime.now.to_i.abs
    complaint.status = "Open"
    complaint
  end

  def remove_phone_numbers complaints
    complaints.each do |c|
      c.mobile = "NA"
    end
  end
end

app/helpers/complaint_helper.rb
module ComplaintHelper
end

app/views/complaints/_form.html.erb
<h2>Register a new complaint</h2>
<%= form_for(@complaint) do |f| %>
  <% if @complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>
      <ul>
      <% @complaint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br />
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br />
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :complaint_type %><br />
    <%= f.select :complaint_type, @complaint.complaint_types  %>
  </div><br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/complaints/create.html.erb
<script>window.location.href = '/complaints/<%= @complaint.id %>'</script>

app/views/complaints/destroy.html.erb
Your complaint is closed. Click <a href="/complaints/new">here</a> to register a new complaint.

app/views/complaints/index.html.erb
<h2>Complaint details</h2>
<table>
  <tr>
    <th>Complaint ID</th>
    <% if current_user %>
      <th>Mobile</th>
    <% end %>
    <th>Name</th>
    <th>Location</th>
    <th>Type</th>
    <th>Status</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Photo URL</th>
  </tr>

  <% @complaints.each do |c| %>
  <tr>
    <td> <%= c.reference_id %> </td>
    <% if current_user %>
      <td> <%= c.mobile %> </td>
    <% end %>
    <td> <%= c.name %> </td>
    <td> <%= c.location %> </td>
    <td> <%= c.complaint_type %> </td>
    <td> <%= c.status %> </td>
    <td> <%= c.latitude %></td>
    <td> <%= c.longitude %></td>
    <td> <%= c.photo_url %></td>
    <td> <%= link_to 'Show', c %></td>
  </tr>
  <% end %>
  </table>
<p>

</p>
<%= link_to 'Register a complaint', new_complaint_path %>

app/views/complaints/new.html.erb
<%= render 'form' %>

<%= link_to 'See Complaints', complaints_path %>

app/views/complaints/report.html.erb
<p>
<h1>Complaint details about Water Leaks</h1>
<table border="1px solid">
  <tr>
    <th>Complaint ID</th>
    <th>Location</th>
    <th>Status</th>
	<th>Photo URL</th>
	<th>Time taken to close the issue</th>
  </tr>

  <% @complaints_wl.each do |c| %>
  <tr>
    <td> <%= c.reference_id %> </td>
    <td> <%= c.location %> </td>
    <td> <%= c.status %> </td>
    <td> <%= c.photo_url %></td>
	<td>
	<% if c.status == "Open" %>
		Not Applicable
	<% else %>
    	<%= c.turn_around_time %>
	<% end %>
	</td>
  </tr>
  <% end %>
  </table>
</p>
<p>
<h1>Complaint details about Water Supply</h1>
<table border="1">
  <tr>
    <th>Complaint ID</th>
    <th>Location</th>
    <th>Status</th>
	<th>Photo URL</th>
	<th>Time taken to close the issue</th>
  </tr>

  <% @complaints_ws.each do |c| %>
  <tr>
    <td> <%= c.reference_id %> </td>
    <td> <%= c.location %> </td>
    <td> <%= c.status %> </td>
    <td> <%= c.photo_url %></td>
	<td>
	<% if c.status == "Open" %>
		Not Applicable
	<% else %>
    	<%= c.turn_around_time %>
	<% end %>
	</td>

  </tr>
  <% end %>
  </table>
</p>
<p>
<h1>Complaint details about Dumping waste in Water</h1>
<table border="1">
  <tr>
    <th>Complaint ID</th>
    <th>Location</th>
    <th>Status</th>
	<th>Photo URL</th>
	<th>Time taken to close the issue</th>
  </tr>

  <% @complaints_wd.each do |c| %>
  <tr>
    <td> <%= c.reference_id %> </td>
    <td> <%= c.location %> </td>
    <td> <%= c.status %> </td>
    <td> <%= c.photo_url %></td>
	<td>
	<% if c.status == "Open" %>
		Not Applicable
	<% else %>
    	<%= c.turn_around_time %>
	<% end %>
	</td>
  </tr>
  <% end %>
  </table>
</p>

app/views/complaints/show.html.erb
<br />
<form id="show">
<table border="1">
<tr>
  <td class="key">Complaint ID</td>
  <td> <%= @complaint.reference_id %> </td>
</tr>
<% if current_user %>
<tr>
  <td class="key">Mobile</td>
  <td> <%= @complaint.mobile %> </td>
</tr>
<% end %>
<tr>
  <td class="key">Location</td>
  <td> <%= @complaint.location %> </td>
</tr>
<tr>
  <td class="key">Complaint Type</td>
  <td> <%= @complaint.complaint_type %> </td>
</tr>
<tr>
  <td class="key">Status</td>
  <td> <%= @complaint.status %> </td>
</tr>
<tr>
  <td class="key">Latitude</td>
  <td> <%= @complaint.latitude %> </td>
</tr>
<tr>
  <td class="key">Longitude</td>
  <td> <%= @complaint.longitude %> </td>
</tr>
<tr>
  <td class="key">Photo URL</td>
  <td>
	<% if @complaint.photo_url == nil || @complaint.photo_url == "No Photo Attached" %>
		No Photo Attached
	<% else %>
		<a href='<%= @complaint.photo_url %>' />
	<% end %>
  </td>
</tr>
</table>
<br />
<% if current_user %>
<%= link_to "Close", @complaint, :method => :delete, :action => 'destroy'%>
<% end %>
</form>
<%= link_to 'Back', complaints_path %> 